package ch.dcreations.apviewer.Step3DModel.StepShapes;

public enum AP242Code {
    LINE,
    SHAPE_DEFINITION_REPRESENTATION,
    VECTOR,
    DIRECTION,
    PRODUCT_DEFINITION_SHAPE,
    ADVANCED_BREP_SHAPE_REPRESENTATION,
    PRODUCT_DEFINITION,
    PRODUCT_DEFINITION_FORMATION,
    PRODUCT,
    PRODUCT_CONTEXT,
    PRODUCT_DEFINITION_CONTEXT,
    APPLICATION_CONTEXT,
    AXIS2_PLACEMENT_3D,
    CARTESIAN_POINT,
    MANIFOLD_SOLID_BREP,
    CLOSED_SHELL,

}
