/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.dcreations.apviewer;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;

import static org.junit.jupiter.api.Assertions.*;

@RunWith(MockitoJUnitRunner.class)
class AppTest {
    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    //@Mock
    //AppTest

}
