/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.dcreations.apviewer;

import ch.dcreations.apviewer.config.LogConfiguration;
import ch.dcreations.apviewer.gui.UI_run;
import ch.dcreations.apviewer.gui.mainViewController;
import javafx.application.Application;

import java.util.logging.Level;
import java.util.logging.Logger;

public class App {

    public static void main(String[] args) {
        // initialize logger level
        LogConfiguration.setLogLevel(mainViewController.class, Level.FINE);
        Application.launch(UI_run.class, args);
    }
}
